/**
 * The simulation.
 *
 * This module and everything under it is pure: no DOM, no Node APIs, no
 * renderer types, no timers, no wall clock. It runs unchanged in a browser
 * worker and in Node, which is what keeps the host swappable and evolution
 * fast (DESIGN.md non-negotiable 1, enforced by sim/tsconfig.json and
 * tests/architecture.test.ts).
 *
 * The contract with the outside world is commands in, snapshots out. Nothing
 * reaches across the boundary in either direction.
 */

export * as math from './math.js';
export { Fuel } from './fuel.js';
export { Metal } from './metal.js';
export { Charge } from './charge.js';
export { Store } from './store.js';
export { Rng, type RngState } from './rng.js';
export {
  Bodies,
  NO_BODY,
  bodyIndex,
  bodyGeneration,
  type BodyId,
  type BodySpec,
} from './bodies.js';
export { World, type ForceProvider, type WorldOptions } from './world.js';
export { AttackArcs, AttackRegion, attackBearing, bestAttackBearings, designArcs } from './attack.js';
export { gravityWell, wellPull, wellPotentialEnergy, type WellSpec } from './gravity.js';
export { SpatialGrid, IndexBuffer, RayHit, segmentCircleT, type RayNarrowPhase } from './spatialGrid.js';
export {
  Projectiles,
  ProjectileHits,
  NO_OWNER,
  NOT_INSIDE,
  type ProjectileSpec,
} from './projectiles.js';
export {
  Beams,
  BeamHits,
  castableBeamLength,
  MAX_BEAM_LENGTH,
  type BeamSpec,
} from './beams.js';
export {
  EngineLayout,
  Allocation,
  applyAllocation,
  shortfall,
  type EngineSpec,
} from './engines.js';
export {
  DECK_HEIGHT,
  BASE_WALL_THICKNESS,
  DEFAULT_NOZZLE_SHARE,
  BARREL_CALIBRES,
  BARREL_OUTER_CALIBRES,
  DEFAULT_HULL_BARREL_CALIBRES,
  MAX_BARREL_CALIBRES,
  BRACE_CALIBRES,
  HULL_APERTURE_FRACTION,
  HULL_BARREL_WIDTH_CAP,
  HULL_CALIBRE_FRACTION,
  CALIBRE_FRACTION,
  HULL_MAX_TRAVERSE,
  NOZZLE_SKIN_FRACTION,
  NOZZLE_THROAT_FRACTION,
  gunStats,
  beamGunStats,
  firingPeriod,
  moduleCentre,
  boxAngle,
  refitModule,
  moduleRadius,
  moduleProblem,
  MODULE_KINDS,
  moduleStats,
  hullBeamStats,
  hullGunStats,
  hullMountGeometry,
  isHullMount,
  countsOutlets,
  readsNozzle,
  readsBarrelCalibres,
  barrelCalibres,
  braceMass,
  readsWeapon,
  readsMain,
  readsThick,
  readsFuse,
  DEFAULT_FUSE,
  casingMass,
  chargeShare,
  DEFAULT_BURST_SPEED,
  DEFAULT_FRAGMENTS,
  EXPLOSIVE_DENSITY,
  SHELL_CALIBRES,
  SHELL_DENSITY,
  firesShells,
  MAX_FRAGMENTS,
  inWeaponsLayer,
  isThick,
  moduleThickness,
  canThicken,
  isWeaponMount,
  mountTraverse,
  FULL_TRAVERSE,
  TRAVERSE_GEAR_FRACTION,
  nozzleOffset,
  weldBox,
  engineGeometry,
  engineExhaustVelocity,
  specificImpulse,
  EXHAUST_VELOCITY,
  SMALL_ENGINE_LOSS,
  FUEL_DENSITY,
  FUEL_DRAG_COEFFICIENT,
  METAL_DENSITY,
  CORE_METAL_SHARE,
  SEALANT_DENSITY,
  SEAL_SPEED,
  SEAL_REACH,
  readsSealing,
  readsDrainPriority,
  readsFill,
  readsDocked,
  fillOf,
  liningOf,
  interiorVolume,
  CORE_COMPUTING_VOLUME,
  STANDARD_GRAVITY,
  engineMachinery,
  traverseAccel,
  mountAccel,
  moduleOutline,
  shapeModule,
  traverseRate,
  TRAVERSE_SPINUP_TIME,
  CLAW_MASS_PER_AREA,
  CLAW_PUMP_PER_METRE,
  PAD_MASS_PER_AREA,
  PAD_PUMP_PER_METRE,
  PORT_MASS_PER_AREA,
  PORT_PUMP_PER_METRE,
  BATTERY_ENERGY_PER_VOLUME,
  BATTERY_MASS_PER_VOLUME,
  BATTERY_POWER_PER_AREA,
  GENERATOR_POWER_PER_VOLUME,
  GENERATOR_MASS_PER_VOLUME,
  type GunStats,
  type BurstStats,
  type ModuleKind,
  type ModuleSpec,
  type HullMountGeometry,
  type ModuleStats,
  type EngineGeometry,
} from './modules.js';
export {
  BOTH_LAYERS,
  HULL_LAYER,
  HullPath,
  Hulls,
  modulesAlong,
  moduleLayers,
  OWN_LAYERS,
  WEAPONS_LAYER,
  type HullDesigns,
} from './hull.js';
export {
  canShape,
  insetTriangle,
  isTriangle,
  normalizeShape,
  polygonArea,
  triangleAcross,
  triangleBounds,
  triangleOf,
  wedge,
  triangleRadius,
  TRIANGLE_CORNERS,
  insideOutline,
  distanceToOutline,
} from './shape.js';
export {
  PLUME_POWER_PER_NEWTON,
  PLUME_RAYS,
  exhaustObstruction,
  ownLanding,
  type PlumeSlice,
  PLUME_CORE_WIDTHS,
  Plumes,
  collimation,
  plumeIntensity,
  WEAPON_PLUME_SHARE,
  weaponPlumeReach,
  nozzleReach,
  plumeRays,
  plumeRayStarts,
  landedIndex,
  landedLength,
  plumeLayers,
  layerCount,
  plumeReach,
  rayOffset,
  rayReach,
} from './exhaust.js';
export {
  DEFAULT_DOCTRINE,
  APPROACH_FIELDS,
  DOCTRINE_FIELDS,
  MOUNT_TARGETING_FIELDS,
  SHIP_TARGETING_FIELDS,
  TARGETING_FIELDS,
  doctrineProblem,
  defaultTargeting,
  doctrineUnread,
  holdBand,
  resolveTargeting,
  serialiseDoctrine,
  serialiseTargeting,
  targetingProblem,
  toDoctrine,
  type Approach,
  type Doctrine,
  type Targeting,
} from './doctrine.js';
export {
  Choice,
  cohesionUrge,
  inSight,
  look,
  score,
  type Candidate,
} from './targeting.js';
export {
  JOINT_IMPULSE_PER_AREA,
  DOCK_HOLD,
  cuts,
  components,
  joints,
  type Cut,
  type Joint,
} from './connectivity.js';
export {
  Collisions,
  Contacts,
  RESTITUTION,
  findContacts,
  resolveContacts,
} from './collision.js';
export {
  ATTACHMENT_TOLERANCE,
  contactWidth,
  assemblyProblem,
  blueprintFaults,
  blueprintProblem,
  blueprintProblems,
  compileBlueprint,
  nominalReach,
  lethalRadius,
  fighterProblem,
  compileDraft,
  layoutStats,
  statsInLayout,
  expandBlueprint,
  expandWithOrigins,
  firingArc,
  barrelHalfWidth,
  triggerMask,
  foldAngle,
  MAX_EXPANDED_MODULES,
  MAX_REPEAT,
  isInstance,
  modulesOverlap,
  placementAt,
  samePlacement,
  subDesign,
  weldDesigns,
  budgetMass,
  footprintOf,
  padHolds,
  aboardPose,
  type Aboard,
  type Seam,
  type Assembly,
  type AssemblyInstance,
  type AssemblyStep,
  type Blueprint,
  type BlueprintFault,
  type Expansion,
  type Frame,
  type ModuleOrigin,
  type ModulePath,
  type PathStep,
  type Placement,
  type DesignModule,
  type DesignTurret,
  type ShipDesign,
} from './blueprint.js';
export {
  pushNeighbours,
  sharedFace,
  shiftSeam,
  withFaceMoved,
  type FaceOf,
  type SharedFace,
} from './push.js';
export {
  BLUEPRINT_FORMAT_VERSION,
  blueprintFileProblem,
  blueprintWarnings,
  degreesToRadians,
  parseBlueprint,
  radiansToDegrees,
  serialiseBlueprint,
} from './blueprintFile.js';
export {
  expandFleet,
  exactTurn,
  fleetProblem,
  isGroupUse,
  MAX_FLEET_SHIPS,
  MAX_FLEET_REPEAT,
  MAX_GROUP_DEPTH,
  shipFleet,
  type Fleet,
  type FleetEntry,
  type FleetGroup,
  type FleetGroupUse,
  type FleetShip,
  type FleetStep,
  type PlacedShip,
  type TrailStep,
} from './fleet.js';
export { FLEET_FORMAT_VERSION, fleetFileProblem, fleetWarnings, parseFleet, serialiseFleet } from './fleetFile.js';
export type { UnreadKeys } from './unread.js';
export {
  centreOf,
  firstOverlap,
  fleetHulls,
  fleetMass,
  fleetReach,
  hullsOverlap,
  placeModules,
  type FleetHull,
} from './fleetHulls.js';
export {
  Turrets,
  FiringSolution,
  interceptTime,
  masked,
  type TurretSpec,
} from './turrets.js';
export {
  Ships,
  NEUTRAL_TEAM,
  NO_TARGET,
  CLAW_BITE,
  CLAW_GRIP_CHANCE,
  CLAW_RETRY,
  CLAW_SPEED_HIGH,
  CLAW_SPEED_LOW,
  CLAW_SPEED_MAX,
  clawChance,
  PAD_SPEED,
  type Order,
  type ShipSpec,
} from './ships.js';
export { capture, Snapshot, type ShipView } from './snapshot.js';
export {
  DE_MARRE_K,
  RICOCHET_ANGLE,
  Terminal,
  deflected,
  incidenceAngle,
  strike,
  type Strike,
} from './ballistics.js';
export {
  Credit,
  DAMAGE_ENERGY_PER_KG,
  RAGGED_INTEGRITY,
  DAMAGE_RESPONSES,
  Damage,
  DamageEffect,
  IMPACT_BEAM,
  IMPACT_BURST,
  IMPACT_COLLISION,
  IMPACT_ROUND,
  ImpactLog,
  Impacts,
  resolveCollision,
  resolveRound,
  type DamageResponse,
  type RoundOutcome,
  type Shocked,
} from './damage.js';
export {
  checksumWorld,
  checksumProjectiles,
  checksumBeams,
  checksumDamage,
  formatChecksum,
} from './checksum.js';
